# Generated by Django 3.2.19 on 2023-07-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="dietary requirements",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="favorite meals",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="food allergies",
        ),
        migrations.AddField(
            model_name="profile",
            name="dietary_requirements",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="food_allergies",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
