# Generated by Django 3.2.19 on 2023-07-20 00:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["booking_date", "booking_time"]},
        ),
    ]
