# Generated by Django 3.2.19 on 2023-07-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_alter_booking_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_name",
            field=models.CharField(default="Ayla", max_length=40),
            preserve_default=False,
        ),
    ]
